### ISSUE TITLE
SendTimestamp: It's there a reason why svg size is 28px?

### ISSUE THREAD

**Issue by ezeholz** [Taimoor-Tariq/BetterDiscordStuff#3]
I just downloaded the plugin, and the first impression of it seems that the icon used isn't in the same size as the other icons.
This image uses 28px size, when every other icon remains in 24px size:
![image](https://user-images.githubusercontent.com/30635862/130378567-38842717-513e-40cb-87ac-27f198ebb0e1.png)
If you change the line below
https://github.com/Taimoor-Tariq/BetterDiscordStuff/blob/261267d3abcf2a7d511ca9e9cb803a19fd691fb0/Plugins/SendTimestamps/SendTimestamps.plugin.js#L67
With the following:
```css
.timestamp-button svg { width: 24px; height: 24px; }
```
The icons would get all the same value.
![image](https://user-images.githubusercontent.com/30635862/130378763-b7c69b76-5d78-400c-85a8-413ed0600c5b.png)

This of course could be changed by using custom css, but I guess that the plugin should stick to the default theme.
```css
/* Custom CSS */

.timestamp-button button svg {
    width: 24px;
    height: 24px;
}
```
